name: 'de_jobs'
version: '1.0.0'

profile: 'de_jobs'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  de_jobs:
    staging:
      +materialized: view
    marts:
      +materialized: view