FROM apache/airflow:2.8.1
COPY airflow_requirements.txt /requirements.txt
RUN pip install --user --upgrade pip
RUN pip install --no-cache-dir --user -r /requirements.txt
RUN mkdir -p /home/airflow/.dbt
COPY airflow_dbt_profile/profiles.yml /home/airflow/.dbt/profiles.yml
